### ISSUE TITLE
Breaking Change: Rename `Assert` and `Select`

### ISSUE THREAD

**Issue by michael-sterling** [Faithlife/FaithlifeTesting#11]
This library intends to use `Select` as "the C# name for monadic bind", but most developers read "Select" as "the thing you call on lists". Further, those familiar with other frameworks may not even realize that `AssertEx.Assert(() => [expression])` returns the value of the expression (after asserting that it's not `null` when `[expression]` is a reference type or nullable value.

It's probably worth a breaking change this early in the library to rename them to:

```
AssertEx.Builder<TClass> HasValue(Expression<Func<TClass>> expression)
   where TClass : class

TValue HasValue<TValue>(Expression<Func<TValue?>> expression)
   where TValue : struct
   
void IsTrue(Expression<Func<bool>> expression)
```

(alongside a parallel rename on the `Builder` extensions).

**Comment by ejball** [comment]
IMHO it would be nice to use names that work well with `using static Faithlife.Testing.AssertEx;` to avoid needing `AssertEx.` all over the place. `Assert` fits that bill.

**Comment by ejball** [comment]
IMHO some form of `NotNull` might be clearer than `HasValue`.

**Comment by michael-sterling** [comment]
Oh, man, where were you *before* I merged this? 😆 

> IMHO it would be nice to use names that work well with `using static Faithlife.Testing.AssertEx`; to avoid needing `AssertEx.` all over the place. `Assert` fits that bill.

This is definitely something I hadn't considered in-depth; I was leaning more towards the NUnit convention of relying on the `AssertEx.` prefix to help communicate -- I'm asserting that the expression is true and/or has a value, not *just* making an assertion.

Still, I'm happy enough with how it looks while `using static Faithlife.Testing.AssertEx` -- in the context of a test suite, I think an `IsTrue(() => isFrobbable);` and `HasValue(() => fooDto);` is still *reasonably* expressive. `Assert(() => isFrobbable);` would *definitely* be beautiful, but in practice I find the expressions aren't always so clean as a well-named boolean and the extra context about what the assertion is checking -- the truthiness -- reads well.

I'm wary of introducing two methods which do the same thing, but agree with you that there were some strong points in `Assert`'s favor. And, when *not* `using static Faithlife.Testing.AssertEx`, the redundancy of `AssertEx.Assert` was a bit grating.

> IMHO some form of `NotNull` might be clearer than `HasValue`.

While watching people adopt AssertEx I found one of the biggest points of confusion was people not spotting the chaining capabilities. `HasValue` is intended to communicate both the "is not null" semantics better than `Select` did, while still emphasizing that the "Value" is relevant -- you can chain on it!
